services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - webnet
    restart: unless-stopped
  
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: taskflow
      MYSQL_USER: taskflow_user
      MYSQL_PASSWORD: taskflow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webnet
    restart: unless-stopped

  app:
    image: sam011103/taskflow:latest
    container_name: taskflow
    volumes:
      - .:/var/www/html
    environment:
      - PORT=9000
      - DEBUG=False
    expose:
      - "9000"
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - mysql

networks:
  webnet:
    driver: bridge

volumes:
  mysql_data: