version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    networks:
      - webnet
    restart: unless-stopped
  app:
    image: sam011103/taskflow:latest
    container_name: taskflow
    volumes:
      - .:/var/www/html
    environment:
      - PORT=5000
      - DEBUG=False
    ports:
      - "5000:5000"
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - nginx