version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - webnet
    restart: unless-stopped
  app:
    image: sam011103/taskflow:latest
    container_name: taskflow
    volumes:
      - .:/var/www/html
    environment:
      - PORT=8000
      - DEBUG=False
    expose:
      - "8000"
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
    driver: bridge